//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int eventId { get; set; }
        public string Sponsor { get; set; }
        public string NameOfEvent { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string EventSite { get; set; }
        public string EventAddress { get; set; }
        public string RoomNights { get; set; }
        public string Attendance { get; set; }
        public string HQHotel { get; set; }
        public string HotelAddress { get; set; }
        public string Description { get; set; }
        public string Time { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string User_ID { get; set; }
    }
}
